import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import JSZip from 'jszip';

function extractCodeBlocks(content) {
  const blocks = [];
  const regex = /```(?:([\w.]+)\n)?([\s\S]*?)```/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    blocks.push({ lang: match[1] || 'txt', code: match[2] });
  }
  return blocks;
}

function detectDeps(code) {
  const deps = {};
  const importRegex = /from ['"]([^./][^'"]*)['"]/g;
  let m;
  while ((m = importRegex.exec(code)) !== null) {
    const pkg = m[1].split('/')[0].replace(/^@[^/]+\/[^/]+.*/, s => s.split('/').slice(0,2).join('/'));
    if (!pkg.startsWith('@/') && !pkg.startsWith('.')) {
      deps[pkg] = 'latest';
    }
  }
  // common known versions
  const knownVersions = {
    react: '^18.2.0', 'react-dom': '^18.2.0', 'react-router-dom': '^6.26.0',
    tailwindcss: '^3.4.0', recharts: '^2.15.4', 'framer-motion': '^11.0.0',
    'lucide-react': '^0.475.0', 'date-fns': '^3.6.0', lodash: '^4.17.21',
    three: '^0.171.0', 'react-three-fiber': '^8.0.0',
  };
  Object.keys(deps).forEach(k => { if (knownVersions[k]) deps[k] = knownVersions[k]; });
  return deps;
}

export default function DownloadButton({ messages, buildTitle }) {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    if (loading) return;
    setLoading(true);

    const zip = new JSZip();
    const src = zip.folder('src');

    // Collect all forge messages
    const forgeMessages = messages.filter(m => m.role === 'forge');
    let allCode = '';
    let fileIndex = 1;

    forgeMessages.forEach(msg => {
      const blocks = extractCodeBlocks(msg.content);
      blocks.forEach(({ lang, code }) => {
        const ext = lang.match(/^(jsx?|tsx?|javascript|typescript)$/) ? 'jsx'
          : lang === 'css' ? 'css'
          : lang === 'json' ? 'json'
          : 'txt';
        const name = ext === 'jsx' ? (fileIndex === 1 ? 'App' : `Component${fileIndex}`) : `file${fileIndex}`;
        src.file(`${name}.${ext}`, code.trim());
        allCode += code;
        fileIndex++;
      });
    });

    if (fileIndex === 1) {
      // No code blocks, save raw content
      forgeMessages.forEach((msg, i) => {
        src.file(`output_${i + 1}.md`, msg.content);
      });
    }

    const deps = detectDeps(allCode);
    deps['react'] = deps['react'] || '^18.2.0';
    deps['react-dom'] = deps['react-dom'] || '^18.2.0';

    const packageJson = {
      name: (buildTitle || 'forge-build').toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
      version: '1.0.0',
      description: `Generated by FORGE Studio — ${buildTitle || 'Build'}`,
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: deps,
      devDependencies: { vite: '^5.0.0', '@vitejs/plugin-react': '^4.0.0' },
    };

    zip.file('package.json', JSON.stringify(packageJson, null, 2));
    zip.file('README.md', `# ${buildTitle || 'FORGE Build'}\n\nGenerated by [FORGE Studio](https://forge.app)\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`);
    zip.file('index.html', `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8"/>\n  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>\n  <title>${buildTitle || 'FORGE Build'}</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/App.jsx"></script>\n</body>\n</html>`);

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(buildTitle || 'forge-build').toLowerCase().replace(/\s+/g, '-')}.zip`;
    a.click();
    URL.revokeObjectURL(url);
    setLoading(false);
  };

  return (
    <button
      onClick={handleDownload}
      disabled={loading || !messages.some(m => m.role === 'forge')}
      className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium rounded-lg border border-border bg-surface-2 hover:border-neon-cyan/40 hover:text-neon-cyan text-muted-foreground transition-all disabled:opacity-40 disabled:cursor-not-allowed"
      title="Download project as ZIP"
    >
      {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
      <span className="hidden sm:inline">Download</span>
    </button>
  );
}